# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1416425061);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1416493554);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.lastDir", "/home/tpbonfi/Pictures");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 10894);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20140621185158");
user_pref("browser.startup.homepage_override.mstone", "24.5.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1416511460388");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1416493495219");
user_pref("datareporting.policy.firstRunTime", "1416425060387");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 25062);
user_pref("datareporting.sessions.current.main", 3778);
user_pref("datareporting.sessions.current.sessionRestored", 25766);
user_pref("datareporting.sessions.current.startTime", "1417719048861");
user_pref("datareporting.sessions.current.totalTime", 77);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1416425052568,\"a\":6,\"t\":38,\"c\":false,\"m\":1478,\"fp\":11954,\"sr\":12854}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1416493318155,\"a\":5,\"t\":39,\"c\":true,\"m\":652,\"fp\":3154,\"sr\":3345}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1416493433436,\"a\":44,\"t\":237,\"c\":true,\"m\":179,\"fp\":1333,\"sr\":1414}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.5.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1415981723000,\"rdfTime\":1403377993000}}}]");
user_pref("extensions.lastAppVersion", "24.5.0");
user_pref("extensions.lastPlatformVersion", "24.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140621185158");
user_pref("gecko.mstone", "24.5.0");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 25688);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1417719052);
user_pref("toolkit.telemetry.previousBuildID", "20140621185158");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1419017067);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
